# -*- coding: utf-8 -*-
"""Twitter sentimental analysis

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1kJxJQT2WDWug_1mYOgG1m1DpUNDD7Y4Y
"""

# Senstimental Analysis of twitter

#importing libraries
import tweepy
from textblob import TextBlob
from wordcloud import WordCloud
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt

#Twitter Credentials
consumerKey='zrYcrLHpb8miuTchOe0BbqDzR'
consumerSecret='O35T9BdKdCQrPOZzNGPgdR4xNrsk9SXlm4qbnBstGji12vzvJR'
accessToken='1022555461755785221-GLFeu1D19k6al6pp9SPownhhxkyTsv'
accessTokenSecret='LDxFAUs5EGmzvBZTk7PYDyBh3Qnv4LVTSqTt16O7Zqzb5'

#authenticating customer credentials
authenticate=tweepy.OAuthHandler(consumerKey,consumerSecret)

#authenticating accessTokens
authenticate.set_access_token(accessToken,accessTokenSecret)

#genrating api
api=tweepy.API(authenticate,wait_on_rate_limit=True)

